{"name": "scenario 1", "status": "broken", "statusDetails": {"message": "RuntimeError: Event loop is closed\n", "trace": "  File \"C:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\Steps.py\", line 36, in sentRequest\n    subSteps.sentRequest()\n  File \"D:\\Hong\\Tester\\AutomationTest\\Playwright\\PlaywrightWithPython\\features\\steps\\SubSteps.py\", line 66, in sentRequest\n    response = self.getRequest(api_request_context)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Hong\\Tester\\AutomationTest\\Playwright\\PlaywrightWithPython\\features\\steps\\SubSteps.py\", line 53, in getRequest\n    return api_request_context.get(wsComponents.getUri(), params=wsComponents.getParameters(),\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\playwright\\sync_api\\_generated.py\", line 18157, in get\n    self._sync(\n  File \"C:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\playwright\\_impl\\_sync_base.py\", line 96, in _sync\n    task: asyncio.tasks.Task[Any] = self._loop.create_task(coro)\n                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\asyncio\\base_events.py\", line 434, in create_task\n    self._check_closed()\n  File \"C:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\asyncio\\base_events.py\", line 519, in _check_closed\n    raise RuntimeError('Event loop is closed')\n"}, "steps": [{"name": "When Init request with protocol=\"https\" and domain=\"api.todoist.com\" and path=\"/rest/v2/comments\" and method=\"GET\" and body=\"None\"", "status": "passed", "start": 1678774949322, "stop": 1678774949322}, {"name": "When Set parameters", "status": "passed", "attachments": [{"name": ".table", "source": "2f727b2d-a203-46e6-8c22-9e02e6e0f299-attachment.csv", "type": "text/csv"}], "start": 1678774949323, "stop": 1678774949324}, {"name": "When Set header", "status": "passed", "attachments": [{"name": ".table", "source": "495b2247-72d4-4947-bf6f-1be74494f74c-attachment.csv", "type": "text/csv"}], "start": 1678774949324, "stop": 1678774949324}, {"name": "When Send request", "status": "broken", "statusDetails": {"message": "RuntimeError: Event loop is closed\n", "trace": "  File \"C:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\Steps.py\", line 36, in sentRequest\n    subSteps.sentRequest()\n  File \"D:\\Hong\\Tester\\AutomationTest\\Playwright\\PlaywrightWithPython\\features\\steps\\SubSteps.py\", line 66, in sentRequest\n    response = self.getRequest(api_request_context)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Hong\\Tester\\AutomationTest\\Playwright\\PlaywrightWithPython\\features\\steps\\SubSteps.py\", line 53, in getRequest\n    return api_request_context.get(wsComponents.getUri(), params=wsComponents.getParameters(),\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\playwright\\sync_api\\_generated.py\", line 18157, in get\n    self._sync(\n  File \"C:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\playwright\\_impl\\_sync_base.py\", line 96, in _sync\n    task: asyncio.tasks.Task[Any] = self._loop.create_task(coro)\n                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\asyncio\\base_events.py\", line 434, in create_task\n    self._check_closed()\n  File \"C:\\Users\\Admin\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\asyncio\\base_events.py\", line 519, in _check_closed\n    raise RuntimeError('Event loop is closed')\n"}, "start": 1678774949324, "stop": 1678774949326}], "start": 1678774949321, "stop": 1678774949327, "uuid": "3a157e36-a6df-4e3c-9751-019d60bd6e39", "historyId": "888e7c20ae68650c382daa829b3ca70a", "fullName": "Test getAllComments: scenario 1", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Test getAllComments"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}